### ISSUE TITLE
Styling corrections added to the To-do list

### ISSUE THREAD

**Issue by keebot-png** [oguntayomicheal/To-Do-list#2]
Well done on passing the review 🥳🥳🥳
The code runs perfectly, however, there are a few styling corrections that I think can be made in order to match the design of the template:

- Try using the table format in the HTML. This will include using the 'table', 'tr', 'th', 'td' tags. The To-do list will look more structured and tidy and does not require advanced CSS to match the template.

**Comment by NurkaAmre** [comment]
Goodjob nothing to commit! merge it 🌷 .

**Comment by Nejjari001** [comment]
Hello @**Micheal**, amazing work with this project 👏 👍
I have noticed the following **JavaScript** good practices:
-No script tags
-Type checks are okay
-Node modules are in the .gitignore file
-No console.logs, no alerts, no document.write or eval()
-No commented out code in the repo
